server:
  port: 10000
  servlet:
    session:
      timeout: 30m

# mysql配置
spring:
  application:
    name: gulimall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.26.160:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: xu.123456
  #    nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
  thymeleaf:
    #    关闭thymeleaf缓存
    cache: false
    #    页面位置
    prefix: classpath:/templates/
  #    指定静态资源位置
  resources:
    static-locations: classpath:/static/

  redis:
    host: 192.168.26.160
    port: 6379
  # spring-cache指定缓存类型
  cache:
    type: redis
    #    指定缓存的过期时间
    redis:
      time-to-live: 3600000
      #      如果指定了前缀，就是用配置文件中的前缀，如果没有配置前缀就是用缓存名作为前缀
      use-key-prefix: true
      #      是否缓存空值，防止缓存穿透
      cache-null-values: true
  session:
    store-type: redis


# mybatis-plus配置
mybatis-plus:
  #  mapper.xml文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  #  id自增
  global-config:
    db-config:
      #      主键自增
      id-type: auto
      logic-delete-field: show_status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
#打印日志
logging:
  level:
    com.xha: debug


#线程池配置
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10




