server:
  port: 30000

spring:
  application:
    name: gulimall-thirdserver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.26.160:8858
        #sentinel监控服务，默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
#   OSS对象存储服务
    alicloud:
      access-key: LTAI5tMp71VYRJkBCsDL9vX7
      secret-key: TWrV2ypCXCVg8ckUu32r9VClqRKMGv
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: imagebed-xuhuaiang
        dir: gulimall
#   短信服务
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        appcode: a3b542043c8e4f4c8508249cf85e45f0
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateIdl: 53e616d338974cba905bd929f4d056ca
        minute: 10
#打印日志
logging:
  level:
    com.xha: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'


