server:
  port: 20000
  servlet:
    session:
      timeout: 30m


spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/

  redis:
    host: 192.168.26.160
    port: 6379
  # spring-cache指定缓存类型
  cache:
    type: redis
    #    指定缓存的过期时间
    redis:
      time-to-live: 3600000
      #      如果指定了前缀，就是用配置文件中的前缀，如果没有配置前缀就是用缓存名作为前缀
      use-key-prefix: true
      #      是否缓存空值，防止缓存穿透
      cache-null-values: true
#      springsession的缓存类型
  session:
    store-type: redis

logging:
  level:
    com.xha.gulimall: debug

feign:
  client:
    config:
      default:
        # 指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间
        ConnectTimeOut: 100000
        # 指的是建立连接后从服务器读取可用资源所用的时间
        ReadTimeOut: 100000


oauth:
  gitee:
    host: https://gitee.com
    path: /oauth/token
    grant_type: authorization_code
    client_id: 6cc5fdfed2ad10ba2e004282103ded8b7ef7be5f734691391f5a5868362a4bd7
    client_secret: e6280cc73ae2d3a102bbab27309b11491ca1b0e30d227aa44ac38bf1c72febb7
    redirect_uri: http://auth.gulimall.com/oauth/gitee

