server:
  port: 50000

spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
  redis:
    host: 192.168.26.160
    port: 6379
