server:
  port: 9000
  servlet:
    session:
      timeout: 30m

# mysql配置
spring:
  application:
    name: gulimall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.26.160:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: xu.123456
  #    nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.26.160:8858
        #sentinel监控服务，默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
  rabbitmq:
    host: 192.168.26.160
    port: 5672
    username: guest
    password: guest
    #    开启消息发送到Bocker的发布确认
    publisher-confirm-type: correlated
    #    开启消息发送到队列的发布确认
    publisher-returns: true
    #    只要消息到达队列,就优先回调ReturenCallback
    template:
      mandatory: true
    #     消费端手动ACK
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    #    关闭thymeleaf缓存
    cache: false
    #    页面位置
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
  session:
    store-type: redis
  redis:
    port: 6379
    host: 192.168.26.160
  #    zipkin
  zipkin:
    base-url: http://192.168.26.160:9411/
    #    关闭zipkin的服务发现
    discovery-client-enabled: false
    #    以http的方式传输数据
    sender:
      type: web
  #      sleuth采样器
  sleuth:
    sampler:
      probability: 1

# mybatis-plus配置
mybatis-plus:
  #  mapper.xml文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  #  id自增
  global-config:
    db-config:
      id-type: auto

feign:
  client:
    config:
      default:
        # 指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间
        ConnectTimeOut: 100000
        # 指的是建立连接后从服务器读取可用资源所用的时间
        ReadTimeOut: 100000
#线程池配置
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
#打印日志
logging:
  level:
    com.xha: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

#支付宝相关设置
alipay:
  #  应用ID,您的APPID
  app_id: 2021000122612368
  #  商户私钥
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCKbFSaR9wok5g0PrwqfUg0Nc7lKISUfn0bQAerCss1SvA1zjAZmwBUKpQp/vRfo2AcXsWPtetG7iI1jCFuBJD7ZtCIjZlyqT+fQ/S4PkL/Q4eEl99HvnS7YGGZocdbklaGBGoF0Ws6hU1b7dEPyPBVEpVim1bb13vfMcDsm9Hy0RWJAH/uzMkeglUtFz9OeNJtNaQ7hXfebxk/B40DqkSNVv562fR6ISoewdVNe0Wk7m4GFKJSzQgu/m6J7zXvvC8hJcnwwPMcZuvR6s+0MQtMUEAYm1Q3+DTgxO/xcsZreWJ12I8cxFsyf9WGdc4Njh/dFo0uHHscxPE9KsdMrFCTAgMBAAECggEAGKWDRtkmrR7iieLltBcMhSdTiF/3g00mT3TOKLlKR1npfVsSG20K2PGf4f5gWqsHUOXa/WSh2MZL1wb1aNZtTiYXWUkFGnJiPqRl7WxAl5zZg1VbTzXtKPPXTPiOO5LJzyD4E8Me+ZOEm6qzf8ECcdNWP/FyvMAYcTw1oqt37WjjuRk/BGjUG2cxAKL2cjIi0aRQ65/yofJUYtcohZ6q4qUuuSsfoGx6jVcPKrtUQTwWksVOTXFbakyDv5jy3JKXi0MQd+O/vdy9/AwvjWK7ppmVJKsb6x2a9to1clC8COzyQAFybLHsrrWOL2fmIcVXL8DlbpflSPYfaAejI4HsYQKBgQDPP0PvLxKU3+FcunMNmPsJkVooSQcyXnqH2n4AmT+dJozvvZhRR78+75cNfzYffajQD7Bzc60r38+t+y1HvvCWFQ5tar06TnFMOF4vNDCgdjNwtkJ8h+m9RekB8T2piHhLGavbUWDl2x3EBAGjt+EH88T0PZBLPEtc3xEByasTcQKBgQCq/GHY6YBoJV7+HJl25j9vZgt5I/II/u+f3k5I5Nne8V+EKw/R2RGUnngwsrn4wBZ5uSRL8hCYMqoF/Y2vU1EGaeijbfy1rQTq/Ci0vJbkela7uMdxg+1AKAeDzp9gBqH78CJhvdKn+72p8F0YozfgiWFHg+avlXVWXboM39jaQwKBgGTYciQnEbGjpzPJ/kY1lKI5Ole0AW5/DrygkwOTjqLXqWjXJxEWCneDeks1BY8ZRFXJ7KChPzjENXiBaq0oukUthdG0SNPga70dCKeLi8Xo/mrwJTYXpKNXK2SokMq3/2D74uZbmP0APGGvWWTjCvsloUb/1gDmG/3bBZmLGlXhAoGBAIhHQ41o/gkD0CRkkwQrG2AkSvywY5Y76qzWuDps/CEu7FwhHii5A8QaUd0udf8GymMV5xIIyqUjrFO99RFKLIgaHWs0nHgIgKTxeVgj/3f28e4Iph2ZcpzxypuJMYmNf8mXaS/R5XYxtMcfZnPekwiJNlmTjWdgjfbaGRFt0B6VAoGAbOsaIyeuM2GCC7jTCuJftETha+fdDK2lMSHtYoDA9ThPVgRkTozvJ23JIxXSva5dANM2qKkwJF9XvUldiZQT8/R4yfbG9R1SNhmz4YuH2oI9SFVs+KESdZLPqVWbFs4Kc0liwofXN2ncJDlXvDxktd2vQ2Hjfemw1MC/H65oiN0=
#  支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0qX/8apeOgsbIhFY9kyS/jdztjb5IUY7+zKVDDuZl4dHrYP6RaH/4lKB32n8CLIiNjbryw5qcrHQQeFP1TJupogkIByoQGpm9j6D/TLh00EZh1VeTxEQbZRJ2pvVym23dHPLgpMVJ+HPqVEBKf8K/QmPb3BHzC7i5Xm3ULkMe5RK0UdWyBHin4HC6S1DWzSATvNsYxS5HjRK05073Oison3iRnYcjyJkGmeqVKvZPaG35UTE+G6QenT5XixkOMLPzzdFqz1vApQTWauZSKDKb7oP7WRv+CDFFw5Ss3UO2TIV6A9iKt4sTF7NB4k2EcrAzU4qNDji3BjIkZwnToTEJQIDAQAB
  #  服务器异步通知页面路径
  notify_url: http://77e18231.r7.cpolar.top/payed/notify
  #  页面跳转同步通知页面路径
  return_url: http://order.gulimall.com/orderlist.html
  #  支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  #  签名方式
  sign_type: RSA2
  #  字符编码格式
  charset: utf-8
