server:
  port: 12000

# mysql配置
spring:
  application:
    name: gulimall-search
  #    nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 192.168.26.160:8858
        #sentinel监控服务，默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
  thymeleaf:
    #    关闭thymeleaf缓存
    cache: false
    #    页面位置
    prefix: classpath:/templates/
  #    指定静态资源位置
  resources:
    static-locations: classpath:/static/
  redis:
    host: 192.168.26.160
    port: 6379

  session:
    store-type: redis

  #    zipkin
  zipkin:
    base-url: http://192.168.26.160:9411/
    #    关闭zipkin的服务发现
    discovery-client-enabled: false
    #    以http的方式传输数据
    sender:
      type: web
  #      sleuth采样器
  sleuth:
    sampler:
      probability: 1

#打印日志
logging:
  level:
    com.xha: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

