server:
  port: 12000

# mysql配置
spring:
  application:
    name: gulimall-search
  #    nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
  thymeleaf:
    #    关闭thymeleaf缓存
    cache: false
    #    页面位置
    prefix: classpath:/templates/
  #    指定静态资源位置
  resources:
    static-locations: classpath:/static/
  redis:
    host: 192.168.26.160
    port: 6379

  session:
    store-type: redis

#打印日志
logging:
  level:
    com.xha: debug

