server:
  port: 40000
# mysql\u914D\u7F6E
spring:
  application:
    name: gulimall-cart
  #    nacos\u914D\u7F6E
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.26.160:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: xu.123456
  redis:
    host: 192.168.26.160
    port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/

# mybatis-plus\u914D\u7F6E
mybatis-plus:
  #  mapper.xml\u6587\u4EF6\u4F4D\u7F6E
  mapper-locations: classpath:/mapper/**/*.xml
  #  id\u81EA\u589E
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.xha.gulimall: debug


