server:
  port: 11000

# mysql配置
spring:
  application:
    name: gulimall-ware
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.26.160:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: xu.123456
  #    nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.160:8848
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
  rabbitmq:
    port: 5672
    host: 192.168.26.160
    username: guest
    password: guest
    listener:
      simple:
#        手动Ack
        acknowledge-mode: manual

# mybatis-plus配置
mybatis-plus:
  #  mapper.xml文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  #  id自增
  global-config:
    db-config:
      id-type: auto
# 打印日志信息
logging:
  level:
    com.xha: debug


